version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-docker
    container_name: laravel-docker-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel-docker
  db:
    image: mysql:8.0
    container_name: laravel-docker-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel-docker
    ports:
      - 3306:3306

  nginx:
    image: nginx:stable-alpine
    container_name: titilaravel-docker-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/laravel.conf
    networks:
      - laravel-docker

networks:
  laravel-docker:
    driver: bridge